export const utils = [
  {
    id: 0,
    gender: "female",
    hint: "",
    status: "Wygłodzenie",
    color: "#00ffd9",
    minBmi: 0,
    maxBmi: 15.99,
    imageSrc: femaleWygłodzenie,
  },
  {
    id: 1,
    gender: "male",
    hint: "",
    status: "Wygłodzenie",
    color: "#00ffd9",
    minBmi: 0,
    maxBmi: 15.99,
    imageSrc: maleWygłodzenie,
  },
  {
    id: 2,
    gender: "female",
    hint: "",
    status: "Wychudzenie",
    color: "#00c187",
    minBmi: 16,
    maxBmi: 16.99,
    imageSrc: femaleWychudzenie,
  },
  {
    id: 3,
    gender: "male",
    hint: "",
    status: "Wychudzenie",
    color: "#00c187",
    minBmi: 16,
    maxBmi: 16.99,
    imageSrc: maleWychudzenie,
  },
  {
    id: 4,
    gender: "female",
    hint: "",
    status: "Niedowaga",
    color: "#008e63",
    minBmi: 17,
    maxBmi: 18.49,
    imageSrc: femaleNiedowaga,
  },
  {
    id: 5,
    gender: "male",
    hint: "",
    status: "Niedowaga",
    color: "#008e63",
    minBmi: 17,
    maxBmi: 18.49,
    imageSrc: maleNiedowaga,
  },
  {
    id: 6,
    gender: "female",
    hint: "",
    status: "Prawidłowa masa ciała",
    color: "#26be00",
    minBmi: 18.5,
    maxBmi: 24.99,
    imageSrc: femalePrawidłowaMasaCiała,
  },
  {
    id: 7,
    gender: "male",
    hint: "",
    status: "Prawidłowa masa ciała",
    color: "#26be00",
    minBmi: 18.5,
    maxBmi: 24.99,
    imageSrc: malePrawidłowaMasaCiała,
  },
  {
    id: 8,
    gender: "female",
    hint: "",
    status: "Nadwaga",
    color: "#ffea00",
    minBmi: 25,
    maxBmi: 29.99,
    imageSrc: femaleNadwaga,
  },
  {
    id: 9,
    gender: "male",
    hint: "",
    status: "Nadwaga",
    color: "#ffea00",
    minBmi: 25,
    maxBmi: 29.99,
    imageSrc: maleNadwaga,
  },
  {
    id: 10,
    gender: "female",
    hint: "",
    status: "Otyłość I stopnia",
    color: "#ff9100",
    minBmi: 30,
    maxBmi: 34.99,
    imageSrc: femaleOtyłośćIStopnia,
  },
  {
    id: 11,
    gender: "male",
    hint: "",
    status: "Otyłość I stopnia",
    color: "#ff9100",
    minBmi: 30,
    maxBmi: 34.99,
    imageSrc: maleOtyłośćIStopnia,
  },
  {
    id: 12,
    gender: "female",
    hint: "",
    status: "Otyłość II stopnia",
    color: "#ff0000",
    minBmi: 35,
    maxBmi: 39.99,
    imageSrc: femaleOtyłośćIIStopnia,
  },
  {
    id: 13,
    gender: "male",
    hint: "",
    status: "Otyłość II stopnia",
    color: "#ff0000",
    minBmi: 35,
    maxBmi: 39.99,
    imageSrc: maleOtyłośćIIStopnia,
  },
  {
    id: 14,
    gender: "female",
    hint: "",
    status: "Otyłość III stopnia",
    color: "#b00000",
    minBmi: 40,
    maxBmi: 9999999,
    imageSrc: femaleOtyłośćIIIStopnia,
  },
  {
    id: 15,
    gender: "male",
    hint: "",
    status: "Otyłość III stopnia",
    color: "#b00000",
    minBmi: 40,
    maxBmi: 9999999,
    imageSrc: maleOtyłośćIIIStopnia,
  },
];
